print(" Mensaje especial")
print("!estoy aprendiendo a usar funciones")
print(" Mensaje especial")
print("!estoy aprendiendo a usar funciones")
print(" Mensaje especial")
print("!estoy aprendiendo a usar funciones")